# Generated by Django 2.1.1 on 2019-06-01 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('price', models.IntegerField()),
                ('company', models.CharField(default='', max_length=50)),
                ('purchase_date', models.DateField(default=datetime.date.today)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
